services:
  couchdb:
    image: apache/couchdb:3 
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin           
      - COUCHDB_PASSWORD=root
    volumes:
      - ./couchdb-data:/opt/couchdb/data
      - ./couchdb-config:/opt/couchdb/etc/local.d
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - couchdb
    environment:
      - COUCHDB_URL=http://admin:root@couchdb:5984/
volumes:
  couchdb_data:

